package pkgfinal;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Chaitanya
 */
public class Display extends javax.swing.JFrame {
Connection con=null;
ResultSet rs=null;
PreparedStatement pst=null;
    /**
     * Creates new form Display
     */
    public Display() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        imglbl = new javax.swing.JLabel();
        tfs = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1300, 700));
        setPreferredSize(new java.awt.Dimension(1300, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(1300, 700));
        getContentPane().setLayout(null);

        tb1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "Employee Name", "Date of Birth", "Gender", "Address", "Salary", "Department No.", "Date Of Joining"
            }
        ));
        tb1.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                tb1MouseWheelMoved(evt);
            }
        });
        tb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 70, 930, 440);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1040, 540, 190, 60);

        imglbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgfinal/di.png"))); // NOI18N
        jDesktopPane2.add(imglbl);
        imglbl.setBounds(0, 0, 280, 370);

        getContentPane().add(jDesktopPane2);
        jDesktopPane2.setBounds(970, 70, 280, 340);

        tfs.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tfs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfsActionPerformed(evt);
            }
        });
        getContentPane().add(tfs);
        tfs.setBounds(350, 540, 220, 60);

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(620, 540, 140, 60);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Table");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(480, 0, 135, 58);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton2.setText("Show");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(70, 540, 150, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgfinal/1227841968.jpg"))); // NOI18N
        jLabel3.setMinimumSize(new java.awt.Dimension(1300, 650));
        jLabel3.setPreferredSize(new java.awt.Dimension(1300, 650));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1920, 1080);

        jDesktopPane1.setMaximumSize(new java.awt.Dimension(1300, 650));
        jDesktopPane1.setMinimumSize(new java.awt.Dimension(1300, 650));
        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(0, 0, 1300, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Main m= new Main();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model =(DefaultTableModel)tb1.getModel();
int rows = model.getRowCount();
if(rows>0){
    for(int i=0;i<rows;i++){
        model.removeRow(0);
    }
}

try{
  Class.forName("com.mysql.jdbc.Driver").newInstance();
  Connection con = (Connection)
  DriverManager.getConnection("jdbc:mysql://localhost:3306/school","root","krishna420");
  String query ="SELECT *FROM employee order by ecode;";
  Statement stmt = con.createStatement();
ResultSet rs = stmt.executeQuery(query);
while(rs.next()){
    String ntNo = rs.getString("ecode");
    String ntName = rs.getString("tName");
    String ndob=rs.getString("Dob");
    String ngender=rs.getString("gender");
    String ntAddress = rs.getString("taddress");
    String nSalary = rs.getString("Salary");
String nDeptno = rs.getString("dept_no");
String ndoj = rs.getString("doj");

System.out.println(ntNo+""+ntName+""+ndob+""+ngender+""+ntAddress+""+nSalary+""+nDeptno+""+ndoj);
model.addRow(new Object[]{ntNo,ntName,ndob,ngender,ntAddress,nSalary,nDeptno,ndoj});
}}
catch(Exception e){
JOptionPane.showMessageDialog(this,e.getMessage());
}
        finally {

            try{

                rs.close();
                pst.close();

            }
            catch(Exception e){

            }
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
                DefaultTableModel model =(DefaultTableModel)tb1.getModel();
int rows = model.getRowCount();
if(rows>0){
    for(int i=0;i<rows;i++){
        model.removeRow(0);
    }
}
        
        try{
     Class.forName("com.mysql.jdbc.Driver").newInstance();
    Connection con = DriverManager.getConnection
            ("jdbc:mysql://localhost:3306/school","root","krishna420");
    Statement stmt = con.createStatement();
    String t=tfs.getText();
    String query = "SELECT  * FROM employee where ecode=" + "'"+t+"'"+ ";";
    ResultSet rs = null;
    System.out.append(query);
    rs = stmt.executeQuery(query);
   
     while(rs.next()){
    String ntNo = rs.getString("ecode");
    String ntName = rs.getString("tName");
    String ndob=rs.getString("Dob");
    String ngender=rs.getString("gender");
    String ntAddress = rs.getString("taddress");
    String nSalary = rs.getString("Salary");
String nDeptno = rs.getString("dept_no");
String ndoj = rs.getString("doj");

        byte[] img = rs.getBytes("ppath");
                ImageIcon imageIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(imglbl.getWidth(), imglbl.getHeight(), Image.SCALE_SMOOTH));
                imglbl.setIcon(imageIcon);
System.out.println(ntNo+""+ntName+""+ndob+""+ngender+""+ntAddress+""+nSalary+""+nDeptno+""+ndoj);
model.addRow(new Object[]{ntNo,ntName,ndob,ngender,ntAddress,nSalary,nDeptno,ndoj});
}
       

   }
    catch(Exception e){
    JOptionPane.showMessageDialog(this,"Record does not exist");
    e.printStackTrace();
   
    }                                        
      finally {
             try{

                rs.close();
                pst.close();

            }
            catch(Exception e){

            }
        
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tfsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfsActionPerformed

    private void tb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb1MouseClicked
        // TODO add your handling code here:
        try{
         int in=tb1.getSelectedRow();
  DefaultTableModel mdl =(DefaultTableModel)tb1.getModel();
              int c=Integer.parseInt(mdl.getValueAt(in,0).toString());
                 Class.forName("com.mysql.jdbc.Driver").newInstance();
    Connection con = DriverManager.getConnection
            ("jdbc:mysql://localhost:3306/school","root","krishna420");
     String query = "SELECT  * FROM employee where ecode='"+c+"'";
    Statement stmt = con.createStatement();
      ResultSet rs = null;
       rs = stmt.executeQuery(query);
   while (rs.next()){
  String pp=(rs.getString(9));
       
        byte[] img = rs.getBytes("ppath");
                ImageIcon imageIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(imglbl.getWidth(), imglbl.getHeight(), Image.SCALE_SMOOTH));
                imglbl.setIcon(imageIcon);
   }
            
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(this,"Record does not exist");
    e.printStackTrace();
   
    }                                        
      finally {

            try{

                rs.close();
                pst.close();

            }
            catch(Exception e){

            }
        }
    }//GEN-LAST:event_tb1MouseClicked

    private void tb1MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_tb1MouseWheelMoved
        // TODO add your handling code here:
          try{
              int in=tb1.getSelectedRow();
  DefaultTableModel mdl =(DefaultTableModel)tb1.getModel();
              int c=Integer.parseInt(mdl.getValueAt(in,0).toString());
                 Class.forName("com.mysql.jdbc.Driver").newInstance();
    Connection con = DriverManager.getConnection
            ("jdbc:mysql://localhost:3306/school","root","krishna420");
     String query = "SELECT  * FROM employee where ecode='"+c+"'";
    Statement stmt = con.createStatement();
      ResultSet rs = null;
       rs = stmt.executeQuery(query);
   while (rs.next()){
  String pp=(rs.getString(9));
       
        byte[] img = rs.getBytes("ppath");
                ImageIcon imageIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(imglbl.getWidth(), imglbl.getHeight(), Image.SCALE_SMOOTH));
                imglbl.setIcon(imageIcon);
   }
            
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(this,"Record does not exist");
    e.printStackTrace();
   
    }                                        
      finally {

            try{

                rs.close();
                pst.close();

            }
            catch(Exception e){

            }
        }
        
    }//GEN-LAST:event_tb1MouseWheelMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Display().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imglbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb1;
    private javax.swing.JTextField tfs;
    // End of variables declaration//GEN-END:variables
}
